### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jmbuhr** [jannikbuhr/ShinyLipids#22]
- [x] PLot Convex Hull first.
- [x] Move Dropdown list.
- [x] Order of Classes
- [ ] Option to order Samples
- [x] Option to remove Error Bars
- [x] Standardize to 100% of sample_replicate as default
- [x] Maybe rename "sample"
- [x] Percent format
- [x] Fix download of csvs
- [x] Nr of Datapoints
- [x] More length's axis labels
- [x] Better Log Axis (and labels)
